project_name: "cd4mt_consistency"
log_directory: "./cm_training_logs"
mode: train
use_wandb: false
seed: 42

id:
  name: "cd4mt_cm_training"
  version: ""

device: "cuda"

# Consistency Model特定配置
cm_config:
  # 训练模式
  training_mode: "consistency_training"  # 使用consistency training而不是distillation

  # EMA参数
  target_ema_mode: "fixed"  # "fixed" | "adaptive"
  start_ema: 0.95

  # Scale参数
  scale_mode: "fixed"  # "fixed" | "progressive" | "progdist"
  start_scales: 40
  end_scales: 40

  # 训练步数
  total_training_steps: 100000
  distill_steps_per_iter: 50000

  # 损失函数
  loss_norm: "l2"  # "l2" | "lpips"

  # 噪声调度
  sigma_min: 0.002
  sigma_max: 80.0
  sigma_data: 0.5
  weight_schedule: "karras"  # "uniform" | "karras"

# 音频到2D映射配置
audio_mapping:
  # 如何将音频latent (B,S,C,L) 映射到 (B,SC,H,W)
  reshape_method: "sqrt"  # "sqrt" | "1d" | "custom"
  min_image_size: 64
  pad_mode: "zero"  # "zero" | "reflect" | "replicate"

trainer:
  accelerator: gpu
  devices: [0]  # 单GPU consistency training
  max_epochs: 50
  save_every: 10
  val_every_n_steps: 1000
  limit_train_batches: 0.1
  limit_val_batches: 0.1
  gradient_clip_val: 1.0
  precision: 32
  resume_from_checkpoint: null

  # CM特定训练参数
  microbatch: -1
  lr: 1e-4
  weight_decay: 0.0
  lr_anneal_steps: 0
  ema_rate: "0.9999"
  log_interval: 10
  save_interval: 1000
  use_fp16: false
  fp16_scale_growth: 1e-3

data:
  target: ldm.data.multitrack_datamodule.DataModuleFromConfig
  params:
    batch_size: 2  # CM训练通常用较小batch size
    num_workers: 2

    augmentation:
      mixup: 0.0
      return_all_wav: False
      balanced_sampling: False

    path:
      dataset_type: "MultiSource_Slakh"
      train_data: /data1/yuchen/MusicLDM-Ext/data/41000/train
      valid_data: /data1/yuchen/MusicLDM-Ext/data/41000/validation
      stems: [bass, drums, guitar, piano]
      test_data: /data1/yuchen/MusicLDM-Ext/data/41000/test
      label_data: ""
      tempo_data: ""
      tempo_map: ""

    preprocessing:
      audio:
        sampling_rate: 44100
        max_wav_value: 32768.0
      stft:
        filter_length: 1024
        hop_length: 512
        win_length: 1024
      mel:
        n_mel_channels: 64
        mel_fmin: 0
        mel_fmax: 8000
        freqm: 0
        timem: 0
        blur: False
        target_length: 1024

# CM模型架构配置（适配音频）
model:
  # 根据音频latent自动配置
  auto_config: true

  # 手动配置（如果auto_config=false）
  manual_config:
    image_size: 64
    num_channels: 128
    num_res_blocks: 2
    channel_mult: "1,2,4"
    attention_resolutions: "32,16,8"
    num_heads: 4
    num_head_channels: 32
    dropout: 0.1
    use_scale_shift_norm: true
    learn_sigma: false
    class_cond: false
    use_fp16: false
    use_checkpoint: false
    use_new_attention_order: false
    resblock_updown: false

  # 音频相关配置
  audio:
    cae_latent_dim: 64
    cae_z_channels: 64
    sample_rate: 44100
    num_stems: 4
    stem_names: ["bass", "drums", "guitar", "piano"]

# 推理采样配置
sampling:
  batch_size: 1
  num_samples: 4
  num_steps: 5  # CM可以用很少的步数采样
  length: 127

  # CM采样参数
  cm_sampling:
    sigma_min: 0.002
    sigma_max: 80.0
    rho: 7.0

# 监控和日志
monitoring:
  metrics: ["train/loss", "val/loss", "consistency_loss"]
  save_samples_every: 500
  log_model_every: 1000